### ISSUE TITLE
Api al real brasilero ?  

### ISSUE THREAD

**Issue by MarcofCorrea** [enzonotario/esjs-dolar-api#1]

**Comment by enzonotario** [comment]
Hola @MarcofCorrea ,

Actualmente la API sólo dispone de la cotización del Dólar, aunque podría agregar otras monedas. Viene bien este Issue para hacerle seguimiento. Lo retomo en unos días.

Saludos!

**Comment by MarcofCorrea** [comment]
🙌🙌🙌🙌

**Comment by enzonotario** [comment]
Hola @MarcofCorrea ,

La API ahora dispone de la cotización del Real Brasileño (y otras monedas). Puedes ver más detalles en: https://dolarapi.com/docs/operations/get-cotizacion-brl.html

Quedo atento a comentarios/sugerencias. Saludos!

**Comment by MarcofCorrea** [comment]
Excelente trabajo @enzonotario  !!!!
