### ISSUE TITLE
Problema con Dólar Tarjeta

### ISSUE THREAD

**Issue by leandroblandi** [enzonotario/esjs-dolar-api#10]
Hola Enzo, al parecer hay un problema con el endpoint del Dólar Tarjeta, devuelve valor 0 de compra y venta. Te adjunto la captura:
![image](https://github.com/enzonotario/esjs-dolar-api/assets/59542421/2b98f8eb-3e4c-4f11-8786-29e689029263)

**Comment by Jesparzarom** [comment]
> Hola Enzo, al parecer hay un problema con el endpoint del Dólar Tarjeta, devuelve valor 0 de compra y venta. Te adjunto la captura:
> ![image](https://github.com/enzonotario/esjs-dolar-api/assets/59542421/2b98f8eb-3e4c-4f11-8786-29e689029263)
> 

Parece que ya está solucionado, compañero de la UNLa 😅!...  ¿Tal vez fue un error de dolarhoy?. Al menos a mí me aparece correctamente.

**Comment by enzonotario** [comment]
Buenas! si, este problema está un poco relacionado a lo discutido en #9. Por lo pronto está corregido, pero también estoy cambiando la Fuente de Datos para evitar estos inconvenientes.

Les aviso por aquí cuando quede para que verifiquen.

**Comment by leandroblandi** [comment]
> > Hola Enzo, al parecer hay un problema con el endpoint del Dólar Tarjeta, devuelve valor 0 de compra y venta. Te adjunto la captura:
> > ![image](https://private-user-images.githubusercontent.com/59542421/290953594-2b98f8eb-3e4c-4f11-8786-29e689029263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjgxNjgsIm5iZiI6MTcwMjg2Nzg2OCwicGF0aCI6Ii81OTU0MjQyMS8yOTA5NTM1OTQtMmI5OGY4ZWItM2U0Yy00ZjExLTg3ODYtMjllNjg5MDI5MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAyNTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMzBjNDM4ZjgzZjFmMGMwODNiYmE1MjI0ZDEzMWQ3NjI3ZThmYTA2ZGJhMzk3OTJlMmM2NjI4ZWNlMjAwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kaxcTeemmVIbj7aTVd_9TLviZgPXT9xRa8hjkv-doo0)
> 
> Parece que ya está solucionado, compañero de la UNLa 😅!... ¿Tal vez fue un error de dolarhoy?. Al menos a mí me aparece correctamente.

Al parecer fue un problema de Dolar Hoy. Estaré atento. Gracias!

**Comment by enzonotario** [comment]
Buenas @leandroblandi @Jesparzarom ,

Ya se encuentran disponibles las cotizaciones según Ámbito Financiero (docs: https://dolarapi.com/docs/ambito/)

De esta manera DolarHoy queda como fuente principal, y AmbitoFinanciero como alternativa, por lo que este inconveniente debería ser mitigado con AmbitoFinanciero como respaldo (además de que la API, en casos que detecte información erronea, al menos muestra el último valor conocido).

Cualquier cosa pueden comentar o abrir otro issue. Saludos!
