### ISSUE TITLE
[New feature] Cotizacion historica

### ISSUE THREAD

**Issue by vSchiaffino** [enzonotario/esjs-dolar-api#11]
Es decir, poder pedir mediante un parametro, el dia en el que se quiere preguntar la cotización

EJEMPLO:
`GET https://dolarapi.com/v1/dolares/bolsa?dia=11/1/2024`
`GET https://dolarapi.com/v1/dolares/bolsa?dia=01/1/2024`
etc
o similar.

**Comment by enzonotario** [comment]
Hola @vSchiaffino , si, tengo pendiente agregar esta Feature, junto con lo mencionado en #3. La característica en sí es fácil de agregar, pero debo hacerlo junto a un mecanismo de autenticación que regule el uso de la API (y evite usos abusivos). Esto lo haré en https://argentinadatos.com/ (y DolarApi.com quedará como una API simple para obtener la cotización actual).

Te aviso por aquí cuando quede (con suerte Q1 2024).

Saludos!

**Comment by vSchiaffino** [comment]
Buenisimo!!

**Comment by enzonotario** [comment]
Buenas @vSchiaffino , esta Feature ya se encuentra disponible en [ArgentinaDatos.com](https://argentinadatos.com/)). Finalmente no fue necesario un mecanismo de autenticación, por lo que también es libre/pública.

La documentación de la API aún no está terminada, pero básicamente los endpoints de cotizaciones son las distintas variaciones de `https://api.argentinadatos.com/v1/cotizaciones/dolares/{casa}/{fecha}`, donde fecha se especifica en el formato `yyyy/MM/dd`. 

Siguiendo tus ejemplos, serían:

`https://api.argentinadatos.com/v1/cotizaciones/dolares/bolsa/2024/01/11`
`https://api.argentinadatos.com/v1/cotizaciones/dolares/bolsa/2024/01/01`

Cualquier cosa, puedes abrir un issue en el repositorio de ArgentinaDatos.

Saludos!

**Comment by vSchiaffino** [comment]
Increible! GRACIAS

**Comment by vSchiaffino** [comment]
Puede ser que solo tenga data desde el 2023/09/08 (formato yyyy/MM/dd) en adelante?

**Comment by enzonotario** [comment]
@vSchiaffino para las Casas `oficial` y `blue`, contamos con datos desde `2011-01-03` (gracias a [Bluelytics](https://bluelytics.com.ar/#!/)). Para el resto de Casas, contamos con datos desde la fecha que indicás (será cuestion de conseguir los datos faltantes e ir expandiendo la Base de Conocimientos).

Puntualmente, puedes ver todos los datos disponibles de la API en la carpeta [`datos`](https://github.com/enzonotario/esjs-argentina-datos-api/tree/main/datos). Si tenés alguna fuente de datos que proporcione los datos faltantes, puedes indicarlo en el repositorio de ArgentinaDatos.com para que sean agregados.

Saludos!

**Comment by vSchiaffino** [comment]
Buenisimo, ahora te tiro la data en el otro repo!
