### ISSUE TITLE
Error en la cotizacion del blue

### ISSUE THREAD

**Issue by ferminrp** [enzonotario/esjs-dolar-api#14]
![CleanShot 2024-02-09 at 11 19 09](https://github.com/enzonotario/esjs-dolar-api/assets/21282919/5fb35657-658d-4c81-8eee-e8068be91319)

Durante unos minutos hoy me encontre con esta respuesta para el blue

**Comment by LucasBussolotti** [comment]
Sigue igual...

**Comment by enzonotario** [comment]
Buenas @ferminrp @LucasBussolotti ya quedó corregido.

Lo que sucede es que la API scrapea la web de DolarHoy, y si el el valor que se muestra allí es incorrecto, el error se propaga a la API (como pueden ver en https://twitter.com/OrcleTa/status/1755958018397659327).

En las próximas semanas implementaré algunos mecanismos que intenten prevenir este inconveniente (por ejemplo, evitando tomar valores que difieran en X% del último valor conocido).

Saludos!

**Comment by LucasBussolotti** [comment]
Buenisimo Enzo, muchas gracias!
