### ISSUE TITLE
Error en iPhone

### ISSUE THREAD

**Issue by daptee** [enzonotario/esjs-dolar-api#17]
Estoy consumiendo en la API correctamente y sin problemas. Lo unico que me esta pasando, que no logro encontrar hasta ahora como resolverlo, es que no me retorna nada si abro la web desde un iphone. Si la web donde tengo implementada la API la abro desde PC o desde celu android, funciona de maravilla, pero desde celu iphone no me trae la informacion. Dejo el codigo que utilizo (VueJS):

methods: {
    async getDolarInfo (pathUrl, dolar) {
      const url = process.env.DOLAR_URL + pathUrl
      try {
        const res = await this.$axios.get(url)
        res.data.forEach((item) => {
          if (this.dolar[item.casa]) {
            this.dolar[item.casa].fecha = item.fechaActualizacion
            this.dolar[item.casa].compra = item.compra
            this.dolar[item.casa].venta = item.venta
          }
        })
        // this.dolar[dolar].fecha = moment(res.data.fechaActualizacion).format('L')
        // this.dolar[dolar].compra = res.data.compra
        // this.dolar[dolar].venta = res.data.venta
        // this.cantDolarGetted++
        return res
      } catch (err) {
        throw err.response
      }
    }
  }

En una prueba que hice, puse un alert(err) en mi catch, y me salto Error Network.

Espero me puedan ayudar. Gracias!

**Comment by enzonotario** [comment]
Hola @daptee , revisa lo siguiente:

1. ¿Te sucede lo mismo con alguna de las [Apps que consumen DolarApi](https://github.com/enzonotario/esjs-dolar-api?tab=readme-ov-file#aplicaciones-que-consumen-esta-api). 
2. ¿Podes subir compartir el proyecto para intentar reproducirlo? o al menos más detalle de cómo están configurada las EnvVars, ya que parece ser un problema de cómo se está armando la solicitud.
3. En el `catch`, agrega un `console.error(err);` para obtener mayores detalles.

Quedo atento. Saludos!

**Comment by daptee** [comment]
Hola @enzonotario gracias por tu respuesta. Te respondo sobre tus dudas.

1. Las aplicaciones que figuran en el git las abri y me funcionan todas bien.
2. el proyecto se puede ver, por si te sirve, en el siguiente link: [](https://gwinn.com.ar/). Si entras y vas para abajo en la web, hay una seccion de las cotizaciones del dolar, y ahi es donde uso la api. Si abris la web desde una PC o celu android vas a ver los datos bien, pero si la abris desde iphone vas a ver todo en 0. Avisame si esto te sirve o necesitas ver si o si el codigo.
3. En el catch, he agregado console log, pero al pasarme el problema en iphone, no puedo acceder a ver que me arroja el console log. Por eso, habia intentando poner un alert en su lugar y me arrojaba Error Network.

Por otro lado, te agregue momentaneamente al repositorio (se llama gwinn-webapp) para que puedas verlo. El componente sobre esto esta en components y se llama Exchange.vue. 

Gracias por la ayuda, quedo atento a tus comentarios.
Saludos!

**Comment by daptee** [comment]
Dejo dicho que ya solucione el tema. La solucion que aplique fue poner la peticion en un archivo .js aparte dentro del directorio services, y utilice axios directamente en lugar de usar $axios. Eso me soluciono el problema ya.
Saludos y gracias igualmente por la ayuda!
