### ISSUE TITLE
El valor de compra del dólar turista retorna "null".

### ISSUE THREAD

**Issue by matiaszozaya** [enzonotario/esjs-dolar-api#2]

**Comment by enzonotario** [comment]
Hola @matiaszozaya , 

Es cierto, pero esto es debido a que el Dólar Turista no es una cotización en realidad, sino que es el valor del Dólar Oficial más impuestos: [Referencia](https://www.dolarsi.com/cotizacion-dolar-turista/).

Aunque claramente es muy confuso, y algunos sitios si muestran valores de compra, e incluso cotizaciones diferente a la de esta API. En el fondo, la API devuelve `compra: null` para el Dólar Turista, básicamente porque dolarhoy.com no muestra un valor de compra (que es la fuente de datos de la API). Si dolarhoy.com mostrase un valor alguna vez, la API también lo hará. Sino, tendríamos que evaluar otra fuente de datos (confiable y estable).

Esto se ve reflejado en el esquema de la respuesta, que indica que `compra` no es `required`: https://dolarapi.com/docs/operations/get-dolar-solidario.html#t-response, aunque también es buena oportunidad para aclararlo en la Documentación.

Si tienes sugerencias para otras fuentes, puedes comentarlas o abrir otro Issue, pero en este momento es esperable que responda con `compra: null`.

Gracias, saludos!

**Comment by matiaszozaya** [comment]
Gracias por la respuesta Enzo! 

Buen trabajo con la Api.

**Comment by z72diego** [comment]
@enzonotario gracias Enzo, perdón, no sabía por donde indicarte el detalle del dólar turista https://app.dolarapi.com/. Muy buen laburo!

**Comment by enzonotario** [comment]
Genial, gracias a ti!

Saludos!
