### ISSUE TITLE
Listar Aplicación

### ISSUE THREAD

**Issue by nehuengiacone** [enzonotario/esjs-dolar-api#20]
# Agregar Aplicación a la lista de aplicaciones que consumen DolarApi.com

## Información de la Aplicación

- **Nombre de la Aplicación:**
CotizArg

- **URL de la Aplicación:**
[Enlace al repositorio](https://github.com/nehuengiacone/CotizArg)

- **Descripción de la Aplicación:**
Sistema de escritorio para consultar las diferentes cotizaciones del dolar en Argentina

**Comment by enzonotario** [comment]
Listo @nehuengiacone . Exitos!

**Comment by nehuengiacone** [comment]
> Listo @nehuengiacone . Exitos!

Gracias!
