### ISSUE TITLE
Error en la cotización del Peso Chileno

### ISSUE THREAD

**Issue by hbjav** [enzonotario/esjs-dolar-api#29]
Buenas! Qué tal?

Estoy viendo un error en la cotización del Peso Chileno, probablemente relacionado con otro issue cerrado que leí recién, donde el valor hay que dividirlo por 100 para que esté bien. Esto es lo que está mostrando ahora:

![imagen](https://github.com/user-attachments/assets/3242d737-d601-482c-998e-c9bf12169039)

Mil gracias por API!!
Saludos!

**Comment by enzonotario** [comment]
Buenas!

En este caso **no** veo que haya diferencia con lo que muestra la Fuente de esta API (DolarHoy.com):

![image](https://github.com/user-attachments/assets/30e48d42-c375-4ef2-a2bb-c75a517dca21)

Y tampoco veo demasiada diferencia con los valores mostrados en El Cronista:

https://www.cronista.com/MercadosOnline/monedas.html

No es necesario dividir este valor por 100. Cierro el issue; si hay algo que entendí mal y persiste el Issue, podes volver a abrirlo.

Gracias, saludos!

**Comment by hbjav** [comment]
Enzo,

Es cierto que ambas páginas dicen que el cambio está a 100, no lo había visto, pero lo cierto es que ambas tienen mal los números... porque el cambio ARS/CLP está alrededor de 1. Fijate acá por ejemplo:

https://themoneyconverter.com/es/CLP/ARS

Saludos!

**Comment by enzonotario** [comment]
Ah bien, en ese caso voy a intentar sacarlo desde InvertirOnline entonces:

https://iol.invertironline.com/mercado/cotizaciones/argentina/monedas

**Comment by enzonotario** [comment]
Buenas @hbjav , ahí quedaron ajustados los valores según InvertirOnline.

Gracias por reportarlo. Saludos!
