### ISSUE TITLE
[New Feature] Añadir cotización del día anterior

### ISSUE THREAD

**Issue by matiaszozaya** [enzonotario/esjs-dolar-api#3]
Sugiero que la API retorne cotizaciones del día anterior, de esa manera se puede calcular fácilmente las variaciones porcentuales.

Ejemplo:

```
[
  "Hoy": {
    "compra": "number",
    "venta": "number",
    "casa": "string",
    "nombre": "string",
    "moneda": "string",
    "fechaActualizacion": "string"
  },
  "Ayer": {
    "compra": "number",
    "venta": "number",
    "casa": "string",
    "nombre": "string",
    "moneda": "string",
    "fechaActualizacion": "string"
  }
]
```

**Comment by enzonotario** [comment]
Hola @matiaszozaya ,

Me parece buena idea, aunque pienso implementar esta (y otras) funcionalidades bajo un mecanismo de autenticación, ya que generarían mayor carga y debo limitarlo a un uso responsable (de `X` peticiones por minuto/hora/dia). Por supuesto, siempre de manera gratuita, pero previo inicio de sesión con algún Proveedor (GitHub/Google/etc), para evitar usos indebidos.

Puntualmente, pienso agregar Endpoints para obtener las Cotizaciones Históricas, de manera que puedan calcularse las variaciones y otras medidas. Este Issue viene bien como seguimiento, aunque se resolverá en semanas/meses, cuando resuelva el mecanismo de autenticación (algo similara a [Unkey](https://unkey.dev/)).

Saludos!

**Comment by matiaszozaya** [comment]
Gracias por contestar nuevamente! Cualquier ayuda que necesites hacemelo saber!

**Comment by Defeeeee** [comment]
Sumado a esto estaria bueno tener una Key que se refiera a la variación en las ultimas 24hs por ejemplo

**Comment by enzonotario** [comment]
Buenas @matiaszozaya @Defeeeee , esta Feature ahora se encuentra disponible en [ArgentinaDatos.com](https://argentinadatos.com/), que es un proyecto paralelo a DolarApi.com, pero enfocado en datos históricos (y cotizaciones en este caso). Finalmente no fue necesario un mecanismo de autenticación, por lo que también es libre/pública.

La documentación de la API aún no está terminada, pero básicamente los endpoints de cotizaciones son las distintas variaciones de `https://api.argentinadatos.com/v1/cotizaciones/dolares/{casa}/{fecha}`, donde `fecha` se especifica en el formato `yyyy/MM/dd`. Pueden revisar el [repositorio de la API](https://github.com/enzonotario/esjs-argentina-datos-api) para entender cuales son los endpoints disponibles, o esperar a que la documentación los refleje. 

También les dejo un ejemplo sencillo de cómo se puede usar para obtener la variación de fechas específicas (obviamente en EsJS, pero pueden obtener el código equivalente en JavaScript en el selector de lenguajes): [Ejemplo para calcular variación](https://editor.esjs.dev/?code=JYWwDg9gTgLghlABAb0QM2iOMA0iDOArgEYAicAnvnnAHZwA2wAXgogL6IAmApvr4gBEtMCAD0XbDwC0aWvjEBqPiEEAoUJFhtUAFR5QQwegw7c%2BAwQAE%2B0gFYKYBoyfVq4%2BYwGMoEWhHRCWi9gP0QIYidaA1IIBgQACi8PODw0Hi8ACzgAShQ1REQvP3wYdAzsgDFMKThJRABedBqYBPSs1KEKbooxAFk%2BiS5BHLUCopKyqD4wQj54RsQZgzZ0mCyE8cKAA0yYGDB8AC4xMTgwYAA6BABzHloYYzrsCHxL4vEANwBGMWLH1ghPx8CRxBAggAkyGS%2BDg7DEUPaVRaPGe7G241G42K8jKDjCTWWUDY03ws3mcEu%2BNoCSxhWmMGg9CQ1LU7DGHm8vn8gWCoVoRUYXkI8SgADUEMA4ECaUjcvlCjjSog6E58IsiGRKPg2hVOt86RNcdwwVBKnrFkS2BEojFTQlBMQGHNBGk9aNFZMTaKAIIPPjmjqWskrJA2%2B520UOp0umj%2B-CGpVlT6S6X8xpbRAJBJcU2B7KXT73BbSb0IP1q-OUosPeViMtQCsBvWF4vygBUiG%2BAAZu2N6TxGVBmYgU1ApTLLmhgHYEKQMqBGHwEgAmUbstRJxCZCAURY%2BVFIKu0zdeygGDUkchUBI7ih4A1jfSGJ4MS58HzAYjAKCbQqCCVxzTMJi2mFUKAvPdVT4cxwIMI5XXGK0kGSBhhVFQCJ35BJzygUYsWfFxGHffBP2-X9xgA1MZXCacQkYJZTG%2BABmMRvhXMQV27FdmIQnAkJDYkUKFEUEEw4CaQPNhj0ELieOkdiFOYkZ8LUIA&layout=horizontal&hidePreview=false&hideEditor=false&hideConsole=false&hideTests=true&readonlyCode=false&readonlyTests=false&preview=%7B%22terminal%22%3Atrue%7D&previewTab=%7B%22console%22%3Atrue%2C%22flowchart%22%3Afalse%2C%22hidden%22%3Afalse%7D&language=esjs&embed=false&hideOptions=false)

De esta manera, DolarApi.com queda destinada a proporcionar la cotización actual, y ArgentinaDatos.com las cotizaciones históricas (por lo que pueden usarse en conjunto para calcular la variación de hoy/ayer). Cualquier cosa, pueden abrir un Issue en el repositorio de ArgentinaDatos.

Saludos!

**Comment by matiaszozaya** [comment]
Muchas gracias por el excelente trabajo @enzonotario. Voy a chequear ArgentinaDatos.

Nuevamente te reitero, cualquier ayuda que necesites hacemelo saber. Estoy a tu disposición.

**Comment by enzonotario** [comment]
Genial @matiaszozaya , acabo de agregar Dolaruco a la [lista de Aplicaciones que consumen la API](https://github.com/enzonotario/esjs-dolar-api?tab=readme-ov-file#aplicaciones-que-consumen-esta-api).

Muchas gracias por el apoyo, e igualmente quedo a disposición por si necesitás algún dato del Dólar o Argentina que podamos agregar en una API.

Saludos!

**Comment by Defeeeee** [comment]
@enzonotario al igual que @matiaszozaya agradezco por el trabajo y por agregar la feature que sugerimos!
En mi caso estoy utilizando tanto DolarApi como ArgentinaDatos para un bot de discord ["DolarBot"](https://github.com/Defeeeee/DolarBot/) que al momento estoy desarrollando.

**Comment by enzonotario** [comment]
Genial @Defeeeee , también acabo de agregar DolarBot a la [lista de Aplicaciones que consumen la API](https://github.com/enzonotario/esjs-dolar-api?tab=readme-ov-file#aplicaciones-que-consumen-esta-api).

Saludos!

**Comment by Defeeeee** [comment]
Gracias! Hay un pequeño detalle, pusiste el link a dolaruco en el vinculo a dolarbot jajaja

**Comment by enzonotario** [comment]
Uh perdón, ahora si quedó bien.

Saludos!
