### ISSUE TITLE
VE paralelo responds null

### ISSUE THREAD

**Issue by agarzon** [enzonotario/esjs-dolar-api#30]
Current data is wrong. Values are just NULL

https://ve.dolarapi.com/v1/dolares/paralelo

Response:
```JSON
{
"fuente": "paralelo",
"nombre": "Paralelo",
"compra": null,
"venta": null,
"promedio": 0,
"fechaActualizacion": "2024-10-18T14:00:33.505Z"
}
```

**Comment by agarzon** [comment]
I used to pull from https://alcambio.app/#/ but I'm not sure if there is any scrapable data in their DOM.

**Comment by enzonotario** [comment]
Great! It looks scrapeable. I'll review it in the next few hours. Thanks!

**Comment by enzonotario** [comment]
@agarzon it's now getting the values from [MonitorDolarVenezuela](https://monitordolarvenezuela.com/). Thanks for reporting!
