### ISSUE TITLE
Error en cotizaciones de Dólar Oficial y Mayorista

### ISSUE THREAD

**Issue by hbjav** [enzonotario/esjs-dolar-api#31]
Hola! Cómo va?

Estoy viendo errores en las cotizaciones de los Dólares Oficial y Mayorista, como si estuvieran atrasados varias semanas. Al parecer tanto dolarhoy.com, dolarito.ar e invertironline.com, por ejemplo, tienen el mismo error. En La Nación el valor del Oficial está bien. Al comparar con los valores oficiales del BCRA se ve la diferencia (https://www.bcra.gob.ar/PublicacionesEstadisticas/Principales_variables.asp --> Tipo de Cambio Minorista / Mayorista).

Ejemplos de hoy 30/10:

• Oficial (Minorista Promedio) BCRA: 1019.74
• Oficial (Promedio) API: 988.5

• Mayorista BCRA: 989.25
• Mayorista API: 962.57

Gracias, saludos!

Javier

**Comment by enzonotario** [comment]
Hola @hbjav , ya quedó corregido el valor del Dólar Mayorista, gracias por reportarlo!

Aunque siguen habiendo diferencias entre los diferentes sitios, ya que entiendo que en realidad son valores de referencia. Aquí tomamos el valor principalmente de DolarHoy.com, y Ambito.com como fuente secundaria. DolarHoy empezó a retornar un valor incorrecto para el Dólar Mayorista, por lo que ahora lo tomamos de Ambito.com.

Según veo, los valores que ahora tenemos (Dólar Oficial desde DolarHoy.com; y Dólar Mayorista desde Ambito.com), difieren de los que se muestran en BCRA, aunque coinciden con los que se muestran en [El Cronista](https://www.cronista.com/MercadosOnline/monedas.html), por lo que considero que ahora están correctos, siempre teniendo en cuenta que son valores de referencia.

Realmente no soy experto en este ámbito, así que si estoy equivocado y hay algo que deba revisar, siéntete libre de re-abrir el Issue para que podamos corregirlo.

Saludos!
