### ISSUE TITLE
Precio Dólar Tarjeta

### ISSUE THREAD

**Issue by lucho-girotti** [enzonotario/esjs-dolar-api#35]
Hola @enzonotario, cómo estás? Después de cambiar el cálculo del dólar tarjeta me quedé pensando... Ahora, y desde hace un tiempo, en dolarhoy.com aparece la cotización del dólar tarjeta, haciendo el cálculo con los impuestos que se le apliquen a esta cotización en la actualidad. Por esto, tal vez sea mejor directamente agarrar este valor, en vez de usar el oficial y agregarle el 30%, ya que los impuestos que se le aplican suelen cambiar (como por ejemplo, la reciente eliminación del impuesto PAIS).
Saludos!

**Comment by enzonotario** [comment]
Buenas @lucho-girotti , es cierto lo que decis, de hecho anteriormente tomabamos el valor directamente desde DolarHoy y lo mostrabamos sin hacer cálculos.

Sin embargo, en un momento DolarHoy estaba realizando cálculos incorrectos, por lo que el error de ellos se propagaba a DolarApi. Por ese motivo decidí calcular manualmente los valores que son calculables. Es decir, prefiero que los valores "calculables" los manejemos nosotros, y no dependamos de terceros. 

Obviamente la desventaja de esto es que si hay cambios externos, necesitamos actualizar manualmente los cálculos, como lo hiciste recientemente en #33 . Aunque incluso ese día recuerdo haber revisado DolarHoy y ellos tampoco tenían el valor actualizado aún. Por lo que, si decidimos tomar los valores de DolarHoy, estamos atados a que ellos actualicen los valores y realicen los cálculos correctos.

Por lo pronto prefiero mantenerlo de esta manera, estoy seguro de que entre todos podemos mantener actualizada esta API rápidamente ante cualquier cambio externo. Siempre son bienvenidos los PRs.

Gracias, saludos!
