### ISSUE TITLE
Euro venta (para calculo de Euro Blue) muy bajo.

### ISSUE THREAD

**Issue by Chota-Cabras** [enzonotario/esjs-dolar-api#4]
Hola!!!
Nunca me coincide el valor del Euro pasando a Dólares según el Banco Central Europeo. La conversión de la API siempre es mucho menor.

Por ejemplo ahora en el BCEuropeo figura 1 EUR = 1.0619 USD
fuente: https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

Sin embargo en la API nos figura 
Euro:   "venta": 370.13,
Dolar Oficial:   "venta": 368.6,

dando un valor de 
1 EUR = 1.004150841020076 USD

Espero sirva el aporte.

**Comment by enzonotario** [comment]
Hola @Chota-Cabras ,

La API simplemente extrae el valor que muestra dolarhoy.com, de manera que estamos sujetos al valor que se muestre en dicha fuente de datos.

Sin embargo, no veo demasiadas diferencias con las cotizaciones que se muestran en otros sitios, por ejemplo:
- https://www.cronista.com/MercadosOnline/moneda.html?id=EUR
- https://www.ambito.com/contenidos/euro.html
- https://www.clarin.com/economia/divisas-acciones-bonos

Por lo tanto, como mencioné en #2 , se espera que la API devuelva los mismos valores que se muestran actualmente en dolarhoy.com. 

Si tienes sugerencias para una mejor fuente de datos (confiable, estable, y completa), puedes comentarlas o abrir otro Issue.

Gracias, saludos!

**Comment by Chota-Cabras** [comment]
Muchas gracias por tomarte la molestia de ir más allá y ver varios valores. Jmmm (¿quién es el que miente? jajaj). Voy a estar analizando. ¡Gracias de nuevo!
