### ISSUE TITLE
Ejemplos: Código Python Erróneo

### ISSUE THREAD

**Issue by Jesparzarom** [enzonotario/esjs-dolar-api#6]
Antes que nada, ¡excelente API!. En cuanto al código python en los ejemplos de la `documentación`, contiene una mezcla de 
`js` y `python`😅 en cada una de las rutas. 

El código básico podría ser algo así para imprimir el dict con cada tipo de cambio:
```python
import requests

data = requests.get("https://dolarapi.com/v1/dolares").json()
for item in data:
    print(item)
```

**Comment by enzonotario** [comment]
Hola @Jesparzarom , muchas gracias por la observación! Ya corregí los ejemplos, tomando el tuyo como base, pero unificando con los ejemplos en otros lenguajes. Quedó: https://dolarapi.com/docs/operations/get-dolares.html#t-samples

Saludos!

**Comment by Jesparzarom** [comment]
Qué rápido.. ¡genial!. No, de nada, quise aportar aunque sea algo ya que la estuve usando este finde para experimentar con https://jesparzarom.github.io/dollargs/ xD. Quedo al pendiente de nuevas funcionalidades 🛠

**Comment by enzonotario** [comment]
¡Excelente! Ahi agregué Dollargs a la [lista de aplicaciones que consumen la API](https://jesparzarom.github.io/dollargs/).

Saludos!

**Comment by Jesparzarom** [comment]
¡Gracias!
