### ISSUE TITLE
[Solicitud] Actualizar impuesto al dolar solidario

### ISSUE THREAD

**Issue by Atosito** [enzonotario/esjs-dolar-api#8]
Buenas. Podrian actualizar el impuesto del calculo del dolar solidario? Q pasaria del 45% al 100%

**Comment by enzonotario** [comment]
Hola @Atosito , creo que hay una confusión entorno a esto.

Primero, la API simplemente toma los valores de DolarHoy.com, por lo que veo que la cotización del "Dólar Solidario" se corresponde correctamente con la que muestra dicha fuente. El día que la fuente actualice el valor de la cotización, la API reflejará ese cambio.

Aunque, veo que muchos sitios toman como iguales al Dólar Solidario y al Dólar Tarjeta. En esta API no son iguales, y en cada uno está su correspondiente descripción:

- Dólar Solidario (75% de impuesto): https://dolarapi.com/docs/operations/get-dolar-solidario.html
- Dólar Tarjeta (155% de impuesto): https://dolarapi.com/docs/operations/get-dolar-tarjeta.html

Por lo tanto, no veo que haya ninguna cotización que esté pasando del 45% al 100%. La noticia que circuló el día 23/11/2023 implicó una actualización en el Dólar Tarjeta, pero no en el Dólar Solidario. Además, fue del 100% al 155%.

¿Queda claro? ¿o a qué cotización te referís? ¿qué fuente tenés de referencia?

Saludos!

**Comment by Jesparzarom** [comment]
Creo que se refería al dólar tarjeta en vez de al dólar solidario, lo que pasa es que si en muchos sitios se presta a confusión. Me parece que se refería al dolar tarjeta pero desglosado que de **45**+25+30 pasó a **100**+25+30. 

Igualmente yo sí lo veo actualizado, conforme DolarHoy.

**Comment by enzonotario** [comment]
Ah perfecto, ahora entiendo que se refería al "Impuesto a las Ganancias". Gracias por la aclaracion!

Si queda algo pendiente por resolver pueden volver a comentar/abrir el issue.

Saludos!
