### ISSUE TITLE
Cotización oficial no actualiza 

### ISSUE THREAD

**Issue by z72diego** [enzonotario/esjs-dolar-api#9]
Hola! El oficial no está actualizando, está 462.40, no 400.50 como marca actualmente la API.

Podrá solucionarse? Gracias!!

**Comment by enzonotario** [comment]
Hola @z72diego recién veo que finalmente abriste el Issue aquí, gracias!

Respecto a lo que mencionas, no es algo que pueda modificar, ya que la API simplemente extrae el valor que se muestra en DolarHoy.com.

Lo único posible sería agregar una nueva Fuente de Datos que sea confiable, actualizada y precisa. ¿Tienes alguna recomendación?

Por lo pronto la Fuente de Datos de la API es DolarHoy.com y veo que los valores se corresponden correctamente. Cuando DolarHoy.com actualice el valor, ese valor se verá reflejado en DolarApi.com.

Saludos!

**Comment by z72diego** [comment]
Esta fuente es de las más confiables!

https://www.ambito.com/contenidos/dolar-html

**Comment by enzonotario** [comment]
Está bien, entonces quizás hay una confusión en el nombre de la cotización. Tanto en la fuente que mencionas, como en DolarHoy.com, indican que el "Dólar Banco Nación" está a $400.50 para la venta. Ese es el valor que informa DolarApi.com, y es el único valor cercano a los $400 que se muestra en DolarHoy.com.

Voy a considerar la fuente que mencionaste como alternativa para agregar, pero se agregará bajo el mecanismo mencionado en #3 (Q1 2024).

Por lo pronto, lo único que podemos esperar es que DolarHoy.com actualice su valor para "Dólar Banco Nación".

Saludos!

**Comment by enzonotario** [comment]
Hola @z72diego veo que los valores acaban de ser actualizado. ¿Por favor me confirmas si ahora son correctos?

(aunque igualmente estoy considerando agregar otras Fuentes de Datos a futuro para evitar estos inconvenientes).

**Comment by z72diego** [comment]
Hola @enzonotario ahora son correctos. Les recomiendo honestamente (porque trabajo con los mercados hace años) que tomen como fuente Ámbito. DolarHoy se utilizaba hace muchos años pero dejó de ser confiable porque no actualizan con tanta frecuencia. Ámbito es lo mejor. Tienen inclusive App para Android y iOS que es por lejos la aplicación de cotizaciones líder. Siempre actualizada! Saludos!

**Comment by z72diego** [comment]
Por ejemplo, la API ahora muestra el dolar oficial a $820, pero en verdad el valor correcto es $833.26, tal como lo muestran diversas fuentes:

https://www.lanacion.com.ar/dolar-hoy/
https://www.ambito.com/contenidos/dolar.html

Si vamos a la única verdad oficial 100% actualizada. Siempre el dólar oficial se va a encontrar en https://www.bcra.gob.ar/PublicacionesEstadisticas/Tipo_de_cambio_minorista_2.asp

**Comment by z72diego** [comment]
La verdad es que para que la API sea 100% confiable, se debería tomar el valor oficial del BCRA y sobre ello aplicar los cálculos que disponga el gobierno de turno para llegar a las otras cotizacones. Es más complejo porque si cambian las disposiciones uds. también tienen que estar actualizando los cálculos. Por eso creo que su mejor opción es tomar Ámbito como referencia que si bien ahora tiene una pequeña diferencia con el BCRA, será corregida en minutos o en un par de horas.

Saludos!

**Comment by z72diego** [comment]
Y gracias, la API funciona bárbaro!

**Comment by enzonotario** [comment]
Perfecto! Yo la verdad soy Desarrollador, y la API simplemente extrae los valores de DolarHoy.com. No soy un experto en finanzas así que me viene bien estas aclaraciones. Durante las próximas semanas haré los ajustes necesarios para que la API refleje mejor la realidad.

Gracias, saludos!

**Comment by z72diego** [comment]
Gracias a vos Enzo, cualquier cosa a tu disposición.

Veo que ahora oficial, solidario y tarjeta devuelve null porque imagino estarás trabajando en ello.

Saludos!

**Comment by enzonotario** [comment]
La verdad que no había tocado nada, pero ocurre que DolarHoy.com modificó su estructura, por lo que tuve que ajustar la API. Ahora ya nuevamente devuelve el valor correcto (aunque se sigue manteniendo la fuente). Cuando ocurran cosas así, no duden en avisar.

También veo que, como comentaste, acaban de quitar el "Dólar Solidario". Luego lo quito de esta API también.

Gracias, saludos!

**Comment by z72diego** [comment]
Si? Aquí sigo viendo null: https://dolarapi.com/docs/operations/get-dolar-oficial.html

**Comment by enzonotario** [comment]
Ahora si (demora en impactar por la cache) :smile:

**Comment by z72diego** [comment]
Buenas! El oficial devuelve null otra vez y en dolarhoy el valor está online 🫠 gracias!

**Comment by enzonotario** [comment]
Buenas! Veo que está devolviendo el valor correcto, aunque luego mejoraré la API para que al menos devuelva el ultimo valor conocido, en vez de `null`.

**Comment by enzonotario** [comment]
Buenas @z72diego,

Ya se encuentran disponibles las cotizaciones según Ámbito Financiero (docs: https://dolarapi.com/docs/ambito/).

De esta manera DolarHoy queda como fuente principal, y AmbitoFinanciero como alternativa, por lo que este inconveniente debería ser mitigado con AmbitoFinanciero como respaldo (además de que la API, en casos que detecte información erronea, al menos muestra el último valor conocido).

Cualquier cosa puedes comentar o abrir otro issue. Saludos!

**Comment by z72diego** [comment]
> Buenas @z72diego,
> 
> Ya se encuentran disponibles las cotizaciones según Ámbito Financiero (docs: https://dolarapi.com/docs/ambito/).
> 
> De esta manera DolarHoy queda como fuente principal, y AmbitoFinanciero como alternativa, por lo que este inconveniente debería ser mitigado con AmbitoFinanciero como respaldo (además de que la API, en casos que detecte información erronea, al menos muestra el último valor conocido).
> 
> Cualquier cosa puedes comentar o abrir otro issue. Saludos!

Un lujo Enzo, me querés compartir un alias de CBU así te envío una donación? Saludos!

**Comment by enzonotario** [comment]
Genial @z72diego , puedes hacerlo por Cafecito: https://cafecito.app/enzonotario, o al alias **enzo.not**

Muchas gracias! Saludos!
